# Jekyll
baseurl: /wireguard-config

exclude:
  - Makefile
  - README.md

  - Gemfile
  - Gemfile.lock
  - vendor/

  - node_modules/
  - package.json
  - package-lock.json

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

# jekyll-github-metadata
repository: egor-tensin/wireguard-config
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme@4ad2cc70618ee3c63fc067e68a8967d27596183c

# Theme settings
settings:
  project:
    name: WireGuard configuration
  author:
    name: Egor Tensin
    email: Egor.Tensin@gmail.com
  links:
    - {rel: apple-touch-icon, sizes: 180x180, href: /assets/favicon/apple-touch-icon.png}
    - {rel: icon, type: image/png, sizes: 32x32, href: /assets/favicon/favicon-32x32.png}
    - {rel: icon, type: image/png, sizes: 16x16, href: /assets/favicon/favicon-16x16.png}
    - {rel: manifest, href: /assets/favicon/site.webmanifest}
