# Jekyll
baseurl: /wireguard-config

exclude:
  - Makefile
  - README.md

  - Gemfile
  - Gemfile.lock
  - vendor/

  - node_modules/
  - package.json
  - package-lock.json

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

# jekyll-github-metadata
repository: egor-tensin/wireguard-config
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme@ba619d5a98dcb86605f850211ab6289d75443416

# Theme settings
settings:
  project:
    name: WireGuard configuration
  author:
    name: Egor Tensin
    email: Egor.Tensin@gmail.com
