# Jekyll
baseurl: /wireguard-config
host: 0.0.0.0
open_url: true
show_drafts: true
strict_front_matter: true

exclude:
  - .wget/
  - DEVELOPMENT.md
  - Makefile
  - prelude.mk
  - README.md

  - package.json
  - package-lock.json

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme
  - jekyll-tidy

# jekyll-github-metadata
repository: egor-tensin/wireguard-config
# jekyll-remote-theme
remote_theme: egor-tensin/jekyll-theme@2028afbf8795e2a42b4799ab3141239d57df3929

# Theme settings
settings:
  project:
    name: WireGuard configuration
  author:
    name: Egor Tensin
    email: egor@tensin.name
  links:
    - {rel: apple-touch-icon, sizes: 180x180, href: /assets/favicon/apple-touch-icon.png}
    - {rel: icon, type: image/png, sizes: 32x32, href: /assets/favicon/favicon-32x32.png}
    - {rel: icon, type: image/png, sizes: 16x16, href: /assets/favicon/favicon-16x16.png}
    - {rel: manifest, href: /assets/favicon/site.webmanifest}
