name: Jekyll

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.6, 2.7]
        version: [Gemfile, latest]
        include:
          - {version: Gemfile, gemfile: Gemfile}
          - {version: latest, gemfile: .ci/Gemfile}
    name: 'Build / ${{ matrix.ruby-version }} / ${{ matrix.version }}'
    env:
      BUNDLE_GEMFILE: '${{ matrix.gemfile }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ matrix.ruby-version }}'
          bundler-cache: true
      - name: jekyll build
        run: bundle exec jekyll build --drafts
      - name: Check integrity
        run: |
          nohup bundle exec jekyll serve --drafts --baseurl '' &
          sleep 3 && wget --no-verbose --recursive --convert-links --adjust-extension --directory-prefix=/tmp -- http://localhost:4000/
